version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081" # Expose Mongo Express web UI port
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017 # Point Mongo Express to MongoDB container
    networks:
      - mongo-network
    depends_on:
      - mongo

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
